// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/attestationpolicy"
	"github.com/in-toto/archivista/ent/predicate"
	"github.com/in-toto/archivista/ent/subjectscope"
)

// SubjectScopeQuery is the builder for querying SubjectScope entities.
type SubjectScopeQuery struct {
	config
	ctx                   *QueryContext
	order                 []subjectscope.OrderOption
	inters                []Interceptor
	predicates            []predicate.SubjectScope
	withAttestationPolicy *AttestationPolicyQuery
	withFKs               bool
	modifiers             []func(*sql.Selector)
	loadTotal             []func(context.Context, []*SubjectScope) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubjectScopeQuery builder.
func (ssq *SubjectScopeQuery) Where(ps ...predicate.SubjectScope) *SubjectScopeQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SubjectScopeQuery) Limit(limit int) *SubjectScopeQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SubjectScopeQuery) Offset(offset int) *SubjectScopeQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SubjectScopeQuery) Unique(unique bool) *SubjectScopeQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SubjectScopeQuery) Order(o ...subjectscope.OrderOption) *SubjectScopeQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QueryAttestationPolicy chains the current query on the "attestation_policy" edge.
func (ssq *SubjectScopeQuery) QueryAttestationPolicy() *AttestationPolicyQuery {
	query := (&AttestationPolicyClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subjectscope.Table, subjectscope.FieldID, selector),
			sqlgraph.To(attestationpolicy.Table, attestationpolicy.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subjectscope.AttestationPolicyTable, subjectscope.AttestationPolicyColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubjectScope entity from the query.
// Returns a *NotFoundError when no SubjectScope was found.
func (ssq *SubjectScopeQuery) First(ctx context.Context) (*SubjectScope, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subjectscope.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SubjectScopeQuery) FirstX(ctx context.Context) *SubjectScope {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubjectScope ID from the query.
// Returns a *NotFoundError when no SubjectScope ID was found.
func (ssq *SubjectScopeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subjectscope.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SubjectScopeQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubjectScope entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubjectScope entity is found.
// Returns a *NotFoundError when no SubjectScope entities are found.
func (ssq *SubjectScopeQuery) Only(ctx context.Context) (*SubjectScope, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subjectscope.Label}
	default:
		return nil, &NotSingularError{subjectscope.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SubjectScopeQuery) OnlyX(ctx context.Context) *SubjectScope {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubjectScope ID in the query.
// Returns a *NotSingularError when more than one SubjectScope ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SubjectScopeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subjectscope.Label}
	default:
		err = &NotSingularError{subjectscope.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SubjectScopeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubjectScopes.
func (ssq *SubjectScopeQuery) All(ctx context.Context) ([]*SubjectScope, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubjectScope, *SubjectScopeQuery]()
	return withInterceptors[[]*SubjectScope](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SubjectScopeQuery) AllX(ctx context.Context) []*SubjectScope {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubjectScope IDs.
func (ssq *SubjectScopeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err = ssq.Select(subjectscope.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SubjectScopeQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SubjectScopeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SubjectScopeQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SubjectScopeQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SubjectScopeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SubjectScopeQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubjectScopeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SubjectScopeQuery) Clone() *SubjectScopeQuery {
	if ssq == nil {
		return nil
	}
	return &SubjectScopeQuery{
		config:                ssq.config,
		ctx:                   ssq.ctx.Clone(),
		order:                 append([]subjectscope.OrderOption{}, ssq.order...),
		inters:                append([]Interceptor{}, ssq.inters...),
		predicates:            append([]predicate.SubjectScope{}, ssq.predicates...),
		withAttestationPolicy: ssq.withAttestationPolicy.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithAttestationPolicy tells the query-builder to eager-load the nodes that are connected to
// the "attestation_policy" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SubjectScopeQuery) WithAttestationPolicy(opts ...func(*AttestationPolicyQuery)) *SubjectScopeQuery {
	query := (&AttestationPolicyClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withAttestationPolicy = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Subject string `json:"subject,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubjectScope.Query().
//		GroupBy(subjectscope.FieldSubject).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *SubjectScopeQuery) GroupBy(field string, fields ...string) *SubjectScopeGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubjectScopeGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = subjectscope.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Subject string `json:"subject,omitempty"`
//	}
//
//	client.SubjectScope.Query().
//		Select(subjectscope.FieldSubject).
//		Scan(ctx, &v)
func (ssq *SubjectScopeQuery) Select(fields ...string) *SubjectScopeSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SubjectScopeSelect{SubjectScopeQuery: ssq}
	sbuild.label = subjectscope.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubjectScopeSelect configured with the given aggregations.
func (ssq *SubjectScopeQuery) Aggregate(fns ...AggregateFunc) *SubjectScopeSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SubjectScopeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !subjectscope.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SubjectScopeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubjectScope, error) {
	var (
		nodes       = []*SubjectScope{}
		withFKs     = ssq.withFKs
		_spec       = ssq.querySpec()
		loadedTypes = [1]bool{
			ssq.withAttestationPolicy != nil,
		}
	)
	if ssq.withAttestationPolicy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, subjectscope.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubjectScope).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubjectScope{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ssq.modifiers) > 0 {
		_spec.Modifiers = ssq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withAttestationPolicy; query != nil {
		if err := ssq.loadAttestationPolicy(ctx, query, nodes, nil,
			func(n *SubjectScope, e *AttestationPolicy) { n.Edges.AttestationPolicy = e }); err != nil {
			return nil, err
		}
	}
	for i := range ssq.loadTotal {
		if err := ssq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *SubjectScopeQuery) loadAttestationPolicy(ctx context.Context, query *AttestationPolicyQuery, nodes []*SubjectScope, init func(*SubjectScope), assign func(*SubjectScope, *AttestationPolicy)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SubjectScope)
	for i := range nodes {
		if nodes[i].attestation_policy_subject_scopes == nil {
			continue
		}
		fk := *nodes[i].attestation_policy_subject_scopes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(attestationpolicy.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "attestation_policy_subject_scopes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssq *SubjectScopeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	if len(ssq.modifiers) > 0 {
		_spec.Modifiers = ssq.modifiers
	}
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SubjectScopeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subjectscope.Table, subjectscope.Columns, sqlgraph.NewFieldSpec(subjectscope.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subjectscope.FieldID)
		for i := range fields {
			if fields[i] != subjectscope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SubjectScopeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(subjectscope.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = subjectscope.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubjectScopeGroupBy is the group-by builder for SubjectScope entities.
type SubjectScopeGroupBy struct {
	selector
	build *SubjectScopeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SubjectScopeGroupBy) Aggregate(fns ...AggregateFunc) *SubjectScopeGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SubjectScopeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubjectScopeQuery, *SubjectScopeGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SubjectScopeGroupBy) sqlScan(ctx context.Context, root *SubjectScopeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubjectScopeSelect is the builder for selecting fields of SubjectScope entities.
type SubjectScopeSelect struct {
	*SubjectScopeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SubjectScopeSelect) Aggregate(fns ...AggregateFunc) *SubjectScopeSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SubjectScopeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubjectScopeQuery, *SubjectScopeSelect](ctx, sss.SubjectScopeQuery, sss, sss.inters, v)
}

func (sss *SubjectScopeSelect) sqlScan(ctx context.Context, root *SubjectScopeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
