// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/attestationpolicy"
	"github.com/in-toto/archivista/ent/subjectscope"
)

// SubjectScopeCreate is the builder for creating a SubjectScope entity.
type SubjectScopeCreate struct {
	config
	mutation *SubjectScopeMutation
	hooks    []Hook
}

// SetSubject sets the "subject" field.
func (ssc *SubjectScopeCreate) SetSubject(s string) *SubjectScopeCreate {
	ssc.mutation.SetSubject(s)
	return ssc
}

// SetScope sets the "scope" field.
func (ssc *SubjectScopeCreate) SetScope(s string) *SubjectScopeCreate {
	ssc.mutation.SetScope(s)
	return ssc
}

// SetAttestationPolicyID sets the "attestation_policy" edge to the AttestationPolicy entity by ID.
func (ssc *SubjectScopeCreate) SetAttestationPolicyID(id int) *SubjectScopeCreate {
	ssc.mutation.SetAttestationPolicyID(id)
	return ssc
}

// SetNillableAttestationPolicyID sets the "attestation_policy" edge to the AttestationPolicy entity by ID if the given value is not nil.
func (ssc *SubjectScopeCreate) SetNillableAttestationPolicyID(id *int) *SubjectScopeCreate {
	if id != nil {
		ssc = ssc.SetAttestationPolicyID(*id)
	}
	return ssc
}

// SetAttestationPolicy sets the "attestation_policy" edge to the AttestationPolicy entity.
func (ssc *SubjectScopeCreate) SetAttestationPolicy(a *AttestationPolicy) *SubjectScopeCreate {
	return ssc.SetAttestationPolicyID(a.ID)
}

// Mutation returns the SubjectScopeMutation object of the builder.
func (ssc *SubjectScopeCreate) Mutation() *SubjectScopeMutation {
	return ssc.mutation
}

// Save creates the SubjectScope in the database.
func (ssc *SubjectScopeCreate) Save(ctx context.Context) (*SubjectScope, error) {
	return withHooks(ctx, ssc.sqlSave, ssc.mutation, ssc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssc *SubjectScopeCreate) SaveX(ctx context.Context) *SubjectScope {
	v, err := ssc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssc *SubjectScopeCreate) Exec(ctx context.Context) error {
	_, err := ssc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssc *SubjectScopeCreate) ExecX(ctx context.Context) {
	if err := ssc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssc *SubjectScopeCreate) check() error {
	if _, ok := ssc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "SubjectScope.subject"`)}
	}
	if v, ok := ssc.mutation.Subject(); ok {
		if err := subjectscope.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SubjectScope.subject": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SubjectScope.scope"`)}
	}
	if v, ok := ssc.mutation.Scope(); ok {
		if err := subjectscope.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SubjectScope.scope": %w`, err)}
		}
	}
	return nil
}

func (ssc *SubjectScopeCreate) sqlSave(ctx context.Context) (*SubjectScope, error) {
	if err := ssc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssc.mutation.id = &_node.ID
	ssc.mutation.done = true
	return _node, nil
}

func (ssc *SubjectScopeCreate) createSpec() (*SubjectScope, *sqlgraph.CreateSpec) {
	var (
		_node = &SubjectScope{config: ssc.config}
		_spec = sqlgraph.NewCreateSpec(subjectscope.Table, sqlgraph.NewFieldSpec(subjectscope.FieldID, field.TypeInt))
	)
	if value, ok := ssc.mutation.Subject(); ok {
		_spec.SetField(subjectscope.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := ssc.mutation.Scope(); ok {
		_spec.SetField(subjectscope.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if nodes := ssc.mutation.AttestationPolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subjectscope.AttestationPolicyTable,
			Columns: []string{subjectscope.AttestationPolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attestationpolicy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.attestation_policy_subject_scopes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubjectScopeCreateBulk is the builder for creating many SubjectScope entities in bulk.
type SubjectScopeCreateBulk struct {
	config
	err      error
	builders []*SubjectScopeCreate
}

// Save creates the SubjectScope entities in the database.
func (sscb *SubjectScopeCreateBulk) Save(ctx context.Context) ([]*SubjectScope, error) {
	if sscb.err != nil {
		return nil, sscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sscb.builders))
	nodes := make([]*SubjectScope, len(sscb.builders))
	mutators := make([]Mutator, len(sscb.builders))
	for i := range sscb.builders {
		func(i int, root context.Context) {
			builder := sscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubjectScopeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sscb *SubjectScopeCreateBulk) SaveX(ctx context.Context) []*SubjectScope {
	v, err := sscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sscb *SubjectScopeCreateBulk) Exec(ctx context.Context) error {
	_, err := sscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscb *SubjectScopeCreateBulk) ExecX(ctx context.Context) {
	if err := sscb.Exec(ctx); err != nil {
		panic(err)
	}
}
