-- Create "attestation_policies" table
CREATE TABLE "attestation_policies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "statement_policies" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "attestation_policies_statements_policies" FOREIGN KEY ("statement_policies") REFERENCES "statements" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "attestationpolicy_name" to table: "attestation_policies"
CREATE INDEX "attestationpolicy_name" ON "attestation_policies" ("name");
-- Create "subject_scopes" table
CREATE TABLE "subject_scopes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "subject" character varying NOT NULL, "scope" character varying NOT NULL, "attestation_policy_subject_scopes" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "subject_scopes_attestation_policies_subject_scopes" FOREIGN KEY ("attestation_policy_subject_scopes") REFERENCES "attestation_policies" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "subjectscope_subject" to table: "subject_scopes"
CREATE INDEX "subjectscope_subject" ON "subject_scopes" ("subject");
